version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions-deps:
        patterns:
          - "*" # Include all GitHub Actions

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    ignore:
      - dependency-name: "typescript"
        versions: [ ">=6.0.0" ]

  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"


  - package-ecosystem: "docker"
    directories:
      - "Dockerfile"
      - "Dockerfile-legacy"
    schedule:
      interval: weekly