ignore:
	- "app/Console/"
	- "app/Http/Controllers/Auth"
	- "app/Http/Middleware/LoginCheck.php"
	- "app/Http/Middleware/VerifyCsrfToken.php"
	- "app/Http/Middleware/RedirectIfAuthenticated.php"
	- "app/Providers/BroadcastServiceProvider.php"
	- "installer/"
	- "install.php"
