ignore:
	- "app/Console/"
	- "app/Exceptions/Handlers/"
	- "app/Exceptions/NotMasterException.php"
	- "app/Exceptions/ComposerNotAvailableException.php"
	- "app/Exceptions/ExecNotAvailableException.php"
	- "app/Exceptions/GitNotAvailableException.php"
	- "app/Exceptions/GitNotExecutableException.php"
	- "app/Exceptions/NoOnlineUpdateException.php"
	- "app/Http/Controllers/Auth"
	- "app/Http/Middleware/LoginCheck.php"
	- "app/Http/Middleware/VerifyCsrfToken.php"
	- "app/Http/Middleware/RedirectIfAuthenticated.php"
	- "app/Providers/BroadcastServiceProvider.php"
