preset: symfony
risky: false
enabled:
  - alpha_ordered_imports
disabled:
  - yoda_style
  - indentation
  - no_tab_indentation
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
    - public
  name: "*.php"
  not-name: "*.blade.php"