risky: false
enabled:
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_after_opening_tag
  - blank_line_before_break
  - blank_line_before_continue
  - blank_line_before_declare
  - blank_line_before_return
  - blank_line_before_throw
  - blank_line_before_try
  - braces
  - cast_spaces
  - class_definition
  - concat_without_spaces
  - const_separation
  - declare_equal_normalize
  - elseif
  - encoding
  - full_opening_tag
  - function_declaration
  - function_typehint_space
  - hash_to_slash_comment
  - heredoc_to_nowdoc
  - include
#  - indentation
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - magic_constant_casing
  - method_argument_space
  - method_separation
  - method_visibility_required
  - native_function_casing
  - new_with_braces
  - no_alias_functions
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_throw
  - no_blank_lines_between_imports
  - no_closing_tag
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_block_blank_lines
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_short_bool_cast
  - no_singleline_whitespace_before_semicolons
  - no_spaces_after_function_name
  - no_spaces_inside_offset
  - no_spaces_inside_parenthesis
  - no_spaces_outside_offset
  - no_trailing_comma_in_list_call
  - no_trailing_comma_in_singleline_array
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - no_unneeded_control_parentheses
  - no_unused_imports
  - no_whitespace_before_comma_in_array
  - no_whitespace_in_blank_line
  - normalize_index_brace
  - object_operator_without_whitespace
  - php_unit_fqcn_annotation
  - phpdoc_align
  - phpdoc_annotation_without_dot
  - phpdoc_indent
  - phpdoc_inline_tag
  - phpdoc_link_to_see
  - phpdoc_no_access
  - phpdoc_no_empty_return
  - phpdoc_no_package
  - phpdoc_no_useless_inheritdoc
  - phpdoc_return_self_reference
  - phpdoc_scalar
  - phpdoc_separation
  - phpdoc_single_line_var_spacing
  - phpdoc_summary
  - phpdoc_to_comment
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name
  - pre_increment
  - print_to_echo
  - property_separation
  - property_visibility_required
  - psr4
  - return_type_declaration
  - self_accessor
  - short_scalar_cast
  - silenced_deprecation_error
  - single_blank_line_at_eof
  - single_blank_line_before_namespace
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - single_line_class_definition
  - single_quote
  - space_after_semicolon
  - standardize_not_equals
  - switch_case_semicolon_to_colon
  - switch_case_space
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unalign_double_arrow
  - unalign_equals
  - unary_operator_spaces
  - unix_line_endings
  - whitespace_after_comma_in_array
disabled:
  - indentation
finder:
  exclude:
    - modules
    - node_modules
    - storage
    - vendor
    - public
  name: "*.php"
  not-name: "*.blade.php"