---
codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 3
    wait_for_ci: true
comment:
  behavior: default
  require_base: false
  require_changes: true
  require_head: true
github_checks:
  annotations: false
coverage:
  precision: 2
  round: down
  status:
    changes: false
    patch: off
    project:
      default:
        target: 90%
ignore:
- "^app/Console/.*"
- "^app/Exceptions/.*"
- "^app/Http/Middleware/VerifyCsrfToken.*"
- "^app/Http/Middleware/VerifyCsrfToken.*"
- "^app/Providers/BroadcastServiceProvider.*"
- "^app/Jobs/UploadSizeVariantToS3Job.php"
# We do not test those
- "^app/Mail/.*"
- "^app/Notifications/.*"
# Legacy shit
- "^app/Legacy/.*"
- "^app/View/.*"
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
