# fly.toml app configuration file generated for lychee-demo on 2023-12-24T12:43:53+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lychee-demo"
primary_region = "ams"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_URL = "https://lychee-demo.fly.dev/"
  APP_ENV = "dev"
  DB_CONNECTION = "sqlite"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "file"
  SESSION_LIFETIME=5
  SESSION_SECURE_COOKIE = "true"
  TRUSTED_PROXIES = "*"
  APP_FORCE_HTTPS = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
