#!/usr/bin/env bash
NO_COLOR="\033[0m"
RED="\033[38;5;009m"
GREEN="\033[38;5;010m"
YELLOW="\033[38;5;011m"
ORANGE="\033[38;5;214m"
LIGHTPURPLE="\033[38;5;177m"
PURPLE="\033[38;5;135m"
CYAN="\033[38;5;014m"
LIGHTBLUE="\033[38;5;39m"
BLUE="\033[38;5;75m"
DARKBLUE="\033[38;5;33m"
LIGHTGRAY="\033[38;5;252m"
DARKGRAY="\033[38;5;242m"
BRIGHTRED="\033[91m"
BOLD="\033[1m"

echo -e $GREEN"pre commit hook start"$NO_COLOR

CURRENT_DIRECTORY=`pwd`
GIT_HOOKS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PROJECT_DIRECTORY="$GIT_HOOKS_DIR/../.."

cd $PROJECT_DIRECTORY;
PHP_CS_FIXER="vendor/bin/php-cs-fixer"

if [ -x "$PHP_CS_FIXER" ]; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        ${PHP_CS_FIXER} fix --config=.php_cs ${line};
        git add "$line";
    done
else
    echo ""
    echo "Please install php-cs-fixer, e.g.:"
    echo ""
    echo "${YELLOW}  composer install${NO_COLOR}"
    echo ""
fi

cd $CURRENT_DIRECTORY;
echo "${RED}pre commit hook finish${NO_COLOR}"
