<?php

/**
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2017-2018 Tobias Reich
 * Copyright (c) 2018-2026 LycheeOrg.
 */

namespace App\Rules;

use App\Exceptions\ConflictingPropertyException;
use App\Exceptions\Internal\LycheeLogicException;
use Illuminate\Contracts\Cache\Lock;
use Illuminate\Contracts\Cache\LockTimeoutException;
use Illuminate\Contracts\Validation\DataAwareRule;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Support\Facades\Cache;

/**
 * Serializes chunk uploads for a given staging file (uuid_name) and rejects
 * a chunk_number that is not exactly one past the last chunk durably
 * appended so far.
 *
 * Without this, an ordinary uploader could replay any non-final chunk (or
 * submit chunks out of order) to grow the staging file on disk without
 * bound, since each individual request is otherwise valid.
 *
 * For chunk_number === 1 the staging file does not exist yet (uuid_name is
 * only generated by the controller after validation), so there is nothing
 * to lock or compare against — this rule is a no-op in that case, and
 * `completeAppend()` bootstraps the cached index once the controller has
 * generated the uuid_name and appended the first chunk.
 */
final class ChunkSequenceRule implements DataAwareRule, ValidationRule
{
	/**
	 * All of the data under validation.
	 *
	 * @var array<string,mixed>
	 */
	private array $data = [];

	private ?Lock $lock = null;

	/**
	 * {@inheritDoc}
	 */
	public function setData(array $data): static
	{
		$this->data = $data;

		return $this;
	}

	/**
	 * {@inheritDoc}
	 */
	public function validate(string $attribute, mixed $value, \Closure $fail): void
	{
		if ($attribute !== 'uuid_name') {
			throw new LycheeLogicException('ChunkSequenceRule: attribute must be "uuid_name"');
		}

		$value = $value === '' ? null : $value;
		$chunk_number = intval($this->data['chunk_number'] ?? 0);

		if ($value === null || $chunk_number <= 1) {
			return;
		}

		if (!is_string($value)) {
			return; // we are going to fail elsewhere (FileUuidRule).
		}

		$lock = Cache::lock(self::lockKey($value), 30);
		try {
			$lock->block(60); // wait up to 60 seconds for the lock to be available
		} catch (LockTimeoutException $e) {
			throw new ConflictingPropertyException('Another request is already uploading this chunk.', $e);
		}

		$last_chunk_number = Cache::get(self::cacheKey($value), 0);
		if ($chunk_number !== $last_chunk_number + 1) {
			$lock->release();
			throw new ConflictingPropertyException('Chunk ' . $chunk_number . ' has already been received or is out of order.');
		}

		$this->lock = $lock;
	}

	/**
	 * Records that $chunk_number has been durably appended to the staging
	 * file identified by $uuid_name, and releases the mutex acquired (if
	 * any) during {@see validate()}.
	 *
	 * Must be called by the controller exactly once, immediately after the
	 * chunk's bytes have been appended to the staging file.
	 */
	public function completeAppend(string $uuid_name, int $chunk_number, bool $is_last_chunk): void
	{
		if ($is_last_chunk) {
			Cache::forget(self::cacheKey($uuid_name));
		} else {
			Cache::put(self::cacheKey($uuid_name), $chunk_number, now()->addDay());
		}

		$this->lock?->release();
		$this->lock = null;
	}

	/**
	 * Releases the mutex acquired during {@see validate()} without
	 * recording any progress. Used when some other field fails validation
	 * after this rule already passed, so the lock is not held for its full
	 * TTL while the controller never runs.
	 */
	public function releaseWithoutCommit(): void
	{
		$this->lock?->release();
		$this->lock = null;
	}

	private static function lockKey(string $uuid_name): string
	{
		return 'photo-upload-lock:' . $uuid_name;
	}

	private static function cacheKey(string $uuid_name): string
	{
		return 'photo-upload-chunk:' . $uuid_name;
	}
}
