body:
  - type: markdown
    attributes:
      value: |
        Create a bug report to help us improve, do not ignore the [REQUIRED] sections.
        We understand this can be frustrating, take your time and relax. We are usually
        pretty quick to answer. :)  
        Valid bug report will be converted into proper issues to track their advancement.
  - type: input
    id: lychee-version
    attributes:
      label: Lychee version
      description: Which version of Lychee are you using? Please provide the full version, e.g. v3.2.6.
      placeholder: v5.1.2
    validations:
      required: true

  - type: dropdown
    id: php-version
    attributes:
      label: Which PHP version are you using?
      options:
        - PHP 8.4
        - PHP 8.3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Detailed description of the problem
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      description: | 
        Which steps do we need to take to reproduce the problem you are having?
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error

  - type: textarea
    attributes:
      label: Diagnostics [REQUIRED]
      description: | 
        Paste here is the content of your diagnostics.  
        *(Settings => Diagnostics or https://example.com/Diagnostics or `php artisan lychee:diagnostics`)*
      placeholder: |
        ```
        Paste result here
        ```

  - type: textarea
    attributes:
      label: Browser & System [REQUIRED]

  - type: checkboxes
    attributes:
      label: Please confirm (incomplete submissions will not be addressed)
      options:
        - label: I have provided easy and step-by-step instructions to reproduce the bug.
          required: true
        - label: I understand my bug report will be removed if I haven't met the criteria above.
          required: true