"""Pydantic request/response schemas for the AI Vision Service API.

These models define the contract between the Python service and Lychee (PHP).
All fields are fully type-annotated; no ``Any`` types are used.
"""

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# /detect - Lychee -> Python (request)  &  Python -> Lychee (callback)
# ---------------------------------------------------------------------------


class DetectRequest(BaseModel):
    """Body sent by Lychee when dispatching a face-detection job.

    ``callback_url`` is intentionally absent: the service reads
    ``VISION_FACE_LYCHEE_API_URL`` from env and posts results there directly.
    """

    photo_id: str
    """Lychee-internal photo identifier (string PK)."""

    photo_path: str
    """Absolute filesystem path on the shared Docker volume.

    The service validates that this path starts with ``VISION_FACE_PHOTOS_PATH``
    before opening the file (path-traversal protection).
    """


class SuggestionResult(BaseModel):
    """A single similar face returned as a suggestion."""

    lychee_face_id: str
    """The Lychee ``Face.id`` of the suggested similar face.

    Stored as ``face_suggestions.suggested_face_id`` in the PHP layer;
    Lychee JOINs to resolve the linked person at read time.
    """

    confidence: float = Field(ge=0.0, le=1.0)
    """Cosine-similarity score (0.0-1.0) between the new embedding and this suggestion."""


class FaceResult(BaseModel):
    """One detected face included in the callback payload."""

    x: float = Field(ge=0.0, le=1.0)
    """Left edge of the bounding box as a fraction of image width."""

    y: float = Field(ge=0.0, le=1.0)
    """Top edge of the bounding box as a fraction of image height."""

    width: float = Field(ge=0.0, le=1.0)
    """Bounding-box width as a fraction of image width."""

    height: float = Field(ge=0.0, le=1.0)
    """Bounding-box height as a fraction of image height."""

    confidence: float = Field(ge=0.0, le=1.0)
    """Detection confidence score from the face detector."""

    embedding_id: str
    """Transient identifier generated by the service for this embedding.

    Echoed back in ``DetectCallbackResponse.faces`` so the service can update
    its embedding store with the ``lychee_face_id`` assigned by Lychee.
    This value is *not* persisted on the Lychee ``Face`` model.
    """

    crop: str
    """Base64-encoded 150x150 JPEG face crop.

    Lychee stores it at ``uploads/faces/{token[0:2]}/{token[2:4]}/{token}.jpg``
    where ``token`` is a random high-entropy string generated by Lychee.
    Only the top ``max_faces_per_photo`` faces (by confidence) are included.
    """

    suggestions: list[SuggestionResult] = []
    """Pre-computed similar faces from the embedding store (may be empty)."""


class DetectCallbackPayload(BaseModel):
    """Payload POSTed by the service to Lychee's results endpoint on success."""

    photo_id: str
    status: str = "success"
    faces: list[FaceResult]


class ErrorCallbackPayload(BaseModel):
    """Payload POSTed by the service to Lychee's results endpoint on failure."""

    photo_id: str
    status: str = "error"
    error_code: str
    """Machine-readable error code (e.g. ``"corrupt_file"``, ``"no_faces"``, ``"oom"``)."""
    message: str
    """Human-readable description of the failure."""


class FaceMapping(BaseModel):
    """Mapping returned by Lychee after processing a successful callback.

    The service uses these to update its embedding store with the stable
    Lychee-assigned ``lychee_face_id`` for each embedding.
    """

    embedding_id: str
    """Echoed from ``FaceResult.embedding_id``."""

    lychee_face_id: str
    """Stable Lychee ``Face.id`` assigned to this embedding."""


class DetectCallbackResponse(BaseModel):
    """200 response body returned by Lychee after a successful callback."""

    faces: list[FaceMapping]


# ---------------------------------------------------------------------------
# /match - Lychee -> Python (multipart file)  &  Python -> Lychee (response)
# ---------------------------------------------------------------------------


class MatchResult(BaseModel):
    """A single candidate face returned from a selfie-match query."""

    lychee_face_id: str
    """Stable Lychee ``Face.id``; resolved to ``person_id`` by Lychee."""

    confidence: float = Field(ge=0.0, le=1.0)
    """Cosine-similarity score between the selfie embedding and this face."""


class MatchResponse(BaseModel):
    """Response body for ``POST /match``."""

    matches: list[MatchResult]
    """Top-N matches above ``VISION_FACE_MATCH_THRESHOLD``, ordered by descending confidence."""


# ---------------------------------------------------------------------------
# DELETE /embeddings - Lychee -> Python
# ---------------------------------------------------------------------------


class DeleteEmbeddingsRequest(BaseModel):
    """Body sent by Lychee to delete face embeddings from the store."""

    face_ids: list[str] = Field(min_length=1)
    """List of Lychee ``Face.id`` values whose embeddings should be removed."""


class DeleteEmbeddingsResponse(BaseModel):
    """Response body for ``DELETE /embeddings``."""

    deleted: int
    """Number of embeddings actually removed (IDs not found are silently skipped)."""


# ---------------------------------------------------------------------------
# POST /cluster - Lychee -> Python
# ---------------------------------------------------------------------------


class ClusterFaceResult(BaseModel):
    """One face's cluster assignment."""

    face_id: str
    """Lychee ``Face.id``."""

    cluster_label: int
    """DBSCAN cluster label. ``-1`` = noise / unassigned."""


class ClusterSuggestion(BaseModel):
    """Cross-cluster face suggestion for UI review."""

    face_id: str
    """The face that should show this suggestion."""

    suggested_face_id: str
    """The suggested similar face from a different cluster."""

    confidence: float = Field(ge=0.0, le=1.0)
    """Cosine-similarity score between the two faces."""


class ClusterResponse(BaseModel):
    """Response body for ``POST /cluster``."""

    total_faces: int
    """Total number of embeddings that were clustered."""

    num_clusters: int
    """Number of distinct clusters found (excluding noise)."""

    labels: list[ClusterFaceResult]
    """Per-face cluster label assignments."""


class ClusterCallbackPayload(BaseModel):
    """Payload POSTed by the service to Lychee's clustering results endpoint on success."""

    model_config = {"validate_assignment": True}

    labels: list[ClusterFaceResult]
    """Per-face cluster label assignments."""

    suggestions: list[ClusterSuggestion] = []
    """Cross-cluster face suggestions (optional)."""


# ---------------------------------------------------------------------------
# /health
# ---------------------------------------------------------------------------


class HealthResponse(BaseModel):
    """Response body for ``GET /health``."""

    status: str
    """``"ok"`` when fully operational; ``"degraded"`` if the model is not loaded."""

    model_loaded: bool
    """Whether the InsightFace model pack has been successfully initialised."""

    embedding_count: int
    """Total number of face embeddings currently stored."""
