#!/bin/sh
# shellcheck disable=SC3040
set -euo

echo "📝 Dumping environment variables to .env file..."

ENV_FILE="/app/.env"
CONFIG_DIR="/app/config"

# List of system/infrastructure variable prefixes to EXCLUDE
# These are Docker, system, or shell variables that should NOT go into Laravel's .env
EXCLUDED_PREFIXES="
PATH
HOME
HOSTNAME
PWD
OLDPWD
SHLVL
TERM
USER
LOGNAME
SHELL
LANG
LC_
DISPLAY
DOCKER_
KUBERNETES_
K8S_
COMPOSE_
_
"

# Extract all env() calls from Laravel config files to build a list of known variables
KNOWN_VARS=""
if [ -d "$CONFIG_DIR" ]; then
  echo "   Scanning $CONFIG_DIR for env() calls..."
  # Find all env() calls in config files and extract the variable names
  # Matches: env('VAR_NAME'), env("VAR_NAME"), env('VAR_NAME', default), etc.
  KNOWN_VARS=$(find "$CONFIG_DIR" -name "*.php" -type f -exec grep -oE "env\(['\"]([A-Z0-9_]+)['\"]" {} \; | sed "s/env(['\"]//g" | sed "s/['\"]//g" | sort -u)
  var_count=$(echo "$KNOWN_VARS" | wc -w)
  echo "   Found $var_count unique environment variables in config files"
else
  echo "⚠️  WARNING: Config directory not found at $CONFIG_DIR"
fi

# Create or truncate the .env file
>"$ENV_FILE"

# Add a header comment
cat >>"$ENV_FILE" <<'EOF'
# Laravel Environment Configuration
# Auto-generated from environment variables
# DO NOT EDIT THIS FILE MANUALLY - changes will be overwritten
#
EOF

# Function to check if a variable is known from config files
# Returns 0 (true) if the variable is found in KNOWN_VARS or matches a known prefix
is_known_var() {
  var_name="$1"

  # If we have no known vars, accept everything (fallback mode)
  [ -z "$KNOWN_VARS" ] && return 0

  # Check for exact match
  for known in $KNOWN_VARS; do
    if [ "$var_name" = "$known" ]; then
      return 0
    fi

    # Check for prefix match (e.g., APP_NAME is in config, accept APP_DEBUG too)
    case "$known" in
    *_*)
      prefix="${known%%_*}_"
      case "$var_name" in
      $prefix*)
        return 0
        ;;
      esac
      ;;
    esac
  done

  return 1
}

# Function to check if a variable should be excluded
# Returns 0 (true) if the variable is a system variable that should be excluded
should_exclude_var() {
  var_name="$1"

  # Check against excluded prefixes
  for excluded in $EXCLUDED_PREFIXES; do
    case "$var_name" in
    $excluded*)
      return 0
      ;;
    esac
  done

  return 1
}

# Export all relevant environment variables
# We use `env` to get all current environment variables
env | while IFS='=' read -r name value; do
  # Skip empty names (shouldn't happen, but be safe)
  [ -z "$name" ] && continue

  # Check if this variable should be excluded or is not known
  if ! should_exclude_var "$name" && is_known_var "$name"; then
    # Handle values that may contain special characters or newlines
    # We need to properly escape the value for the .env file

    # If value contains newline, quotes, or special chars, wrap in quotes
    case "$value" in
    *$'\n'* | *\"* | *\'* | *\$* | *\`* | *\\* | *" "* | *"="*)
      # Escape backslashes and double quotes
      escaped_value=$(printf '%s' "$value" | sed 's/\\/\\\\/g; s/"/\\"/g')
      echo "$name=\"$escaped_value\"" >>"$ENV_FILE"
      ;;
    *)
      # Simple value, no quotes needed
      echo "$name=$value" >>"$ENV_FILE"
      ;;
    esac
  fi
done

# Ensure the file is readable
chmod 644 "$ENV_FILE"

echo "✅ Environment variables written to $ENV_FILE"

# Count how many variables were written
var_count=$(grep -v '^#' "$ENV_FILE" | grep -v '^$' | wc -l)
echo "   Exported $var_count environment variables"
