<?php

/**
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2017-2018 Tobias Reich
 * Copyright (c) 2018-2026 LycheeOrg.
 */

namespace App\Enum;

enum NsfwDetectionLabel: string
{
	case FEMALE_GENITALIA_COVERED = 'FEMALE_GENITALIA_COVERED';
	case FACE_FEMALE = 'FACE_FEMALE';
	case BUTTOCKS_EXPOSED = 'BUTTOCKS_EXPOSED';
	case FEMALE_BREAST_EXPOSED = 'FEMALE_BREAST_EXPOSED';
	case FEMALE_GENITALIA_EXPOSED = 'FEMALE_GENITALIA_EXPOSED';
	case MALE_BREAST_EXPOSED = 'MALE_BREAST_EXPOSED';
	case ANUS_EXPOSED = 'ANUS_EXPOSED';
	case FEET_EXPOSED = 'FEET_EXPOSED';
	case BELLY_COVERED = 'BELLY_COVERED';
	case FEET_COVERED = 'FEET_COVERED';
	case ARMPITS_COVERED = 'ARMPITS_COVERED';
	case ARMPITS_EXPOSED = 'ARMPITS_EXPOSED';
	case FACE_MALE = 'FACE_MALE';
	case BELLY_EXPOSED = 'BELLY_EXPOSED';
	case MALE_GENITALIA_EXPOSED = 'MALE_GENITALIA_EXPOSED';
	case ANUS_COVERED = 'ANUS_COVERED';
	case FEMALE_BREAST_COVERED = 'FEMALE_BREAST_COVERED';
	case BUTTOCKS_COVERED = 'BUTTOCKS_COVERED';
}
