<?php

/**
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2017-2018 Tobias Reich
 * Copyright (c) 2018-2026 LycheeOrg.
 */

use App\Models\Extensions\BaseConfigMigration;

return new class() extends BaseConfigMigration {
	public const MOD_WELCOME = 'Mod Welcome';
	public const LAYOUT = 'classic|portfolio|meridian|studio';
	public const TEXT_POSITION = 'top_left|top_right|bottom_left|bottom_right|center';
	public const ANIMATION_PRESET = 'none|classic_fade|zoom_in|parallax_scroll|slide_reveal';
	public const FEATURED_ITEMS_MODE = 'automatic|manual';
	public const FEATURED_COUNT_RANGE = 'int:3:100';
	public const CTA_POSITION = 'top-left|top|top-right|left|center|right|bottom-left|bottom|bottom-right';
	public const SHIFT_TYPE = 'relative|absolute';
	public const SHIFT_X_DIRECTION = 'left|right';
	public const SHIFT_Y_DIRECTION = 'up|down';
	public const PERCENT_RANGE = 'int:0:100';
	public const LOGIN_POSITION = 'side|center';

	public function getConfigs(): array
	{
		return [
			[
				'key' => 'landing_layout',
				'value' => 'classic',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::LAYOUT,
				'description' => 'Landing page layout',
				'details' => 'Options: classic (default, free), portfolio/meridian/studio (require Lychee SE).',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 0,
				'order' => 13,
			],
			[
				'key' => 'landing_intro_screen_enabled',
				'value' => '1',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::BOOL,
				'description' => 'Enable the animated intro splash screen',
				'details' => 'Applies to every layout. Disable to skip straight to the hero.',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 0,
				'order' => 14,
			],
			[
				'key' => 'landing_hero_text_position',
				'value' => 'center',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::TEXT_POSITION,
				'description' => 'Hero headline/subtitle/CTA position',
				'details' => 'Applies to the portfolio layout.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 15,
			],
			[
				'key' => 'landing_hero_text_color',
				'value' => '',
				'cat' => self::MOD_WELCOME,
				'type_range' => 'color',
				'description' => 'Hero headline/subtitle text color',
				'details' => 'Leave empty to use the default white. Applies to the headline and subtitle text on the portfolio and studio layouts.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 16,
			],
			[
				'key' => 'landing_hero_text_opacity',
				'value' => '100',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::PERCENT_RANGE,
				'description' => 'Hero headline/subtitle text opacity (%)',
				'details' => 'Range 0-100. Applies to the headline and subtitle text on the portfolio and studio layouts.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 17,
			],
			[
				'key' => 'landing_animation_preset',
				'value' => 'classic_fade',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::ANIMATION_PRESET,
				'description' => 'Landing page animation preset',
				'details' => 'Options: none/classic_fade (free), zoom_in/parallax_scroll/slide_reveal (require Lychee SE).',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 18,
			],
			[
				'key' => 'landing_about_enabled',
				'value' => '0',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::BOOL,
				'description' => 'Enable the about section',
				'details' => 'Applies to the portfolio and studio layouts.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 19,
			],
			[
				'key' => 'landing_about_text',
				'value' => '',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::STRING,
				'description' => 'About section text',
				'details' => 'Admin-authored HTML, rendered verbatim (same trust model as the footer additional text).',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 20,
			],
			[
				'key' => 'landing_featured_items_enabled',
				'value' => '0',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::BOOL,
				'description' => 'Enable the featured content section (SE)',
				'details' => 'Applies to the portfolio layout only. Requires Lychee SE to take effect.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 21,
			],
			[
				'key' => 'landing_featured_items_mode',
				'value' => 'automatic',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::FEATURED_ITEMS_MODE,
				'description' => 'Featured content mode',
				'details' => 'Automatic: most recently published public albums. Manual: admin-curated photos/albums.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 22,
			],
			[
				'key' => 'landing_featured_items_count',
				'value' => '24',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::FEATURED_COUNT_RANGE,
				'description' => 'Number of automatic featured items',
				'details' => 'Range 3-100. Only used in automatic featured content mode.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 23,
			],
			[
				'key' => 'landing_cta_text',
				'value' => '',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::STRING,
				'description' => 'Primary call-to-action text override',
				'details' => 'Leave empty to use each layout\'s default label.',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 0,
				'order' => 24,
			],
			[
				'key' => 'landing_cta_position',
				'value' => 'bottom',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::CTA_POSITION,
				'description' => 'Call-to-action button anchor position',
				'details' => 'Applies to the classic, meridian, studio and portfolio layouts, independently of the hero text position.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 25,
			],
			[
				'key' => 'landing_cta_shift_type',
				'value' => 'relative',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::SHIFT_TYPE,
				'description' => 'Shift the CTA relatively to the viewport',
				'details' => 'When using relative, the CTA will be shifted proportionally to the size of the viewport.<br>When using absolute the CTA will be shifted by a quantity of pixels.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 26,
			],
			[
				'key' => 'landing_cta_shift_x',
				'value' => '0',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::INT,
				'description' => 'CTA horizontal shift',
				'details' => 'Number of pixel/proportional translation applied horizontally to the CTA anchor.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 27,
			],
			[
				'key' => 'landing_cta_shift_x_direction',
				'value' => 'right',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::SHIFT_X_DIRECTION,
				'description' => 'Direction of the CTA horizontal shift',
				'details' => 'Direction of the translation applied to the CTA: to the left or to the right?',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 28,
			],
			[
				'key' => 'landing_cta_shift_y',
				'value' => '30',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::INT,
				'description' => 'CTA vertical shift',
				'details' => 'Number of pixel/proportional translation applied vertically to the CTA anchor.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 29,
			],
			[
				'key' => 'landing_cta_shift_y_direction',
				'value' => 'up',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::SHIFT_Y_DIRECTION,
				'description' => 'Direction of the CTA vertical shift',
				'details' => 'Direction of the translation applied to the CTA: up or down?',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 30,
			],
			[
				'key' => 'landing_meridian_explore_offset',
				'value' => '42',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::PERCENT_RANGE,
				'description' => 'Meridian: explore rail vertical position (%)',
				'details' => 'How far down the full-height rail the "explore" label sits. 0 is the top, 100 is the bottom. Applies to the meridian layout only.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 31,
			],
			[
				'key' => 'landing_meridian_contact_offset',
				'value' => '70',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::PERCENT_RANGE,
				'description' => 'Meridian: contact rail vertical position (%)',
				'details' => 'How far down the full-height rail the "contact" label sits. 0 is the top, 100 is the bottom. Applies to the meridian layout only.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 32,
			],
			[
				'key' => 'landing_meridian_explore_line_position',
				'value' => '33',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::PERCENT_RANGE,
				'description' => 'Meridian: explore rail horizontal position (%)',
				'details' => 'How far from the left edge the "explore" rail sits. 0 is the left edge, 100 is the right edge. Applies to the meridian layout only; ignored (rail centers itself) when the contact rail is off, since a single rail off-center looks like a mistake rather than a choice.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 33,
			],
			[
				'key' => 'landing_meridian_contact_line_position',
				'value' => '67',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::PERCENT_RANGE,
				'description' => 'Meridian: contact rail horizontal position (%)',
				'details' => 'How far from the left edge the "contact" rail sits. 0 is the left edge, 100 is the right edge. Applies to the meridian layout only.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 34,
			],
			[
				'key' => 'landing_login_position',
				'value' => 'side',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::LOGIN_POSITION,
				'description' => 'Login panel position',
				'details' => 'Applies to the studio layout. Side pins the login panel to the reading-direction edge on wide screens; it always centers below the hero on narrow screens regardless of this setting.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 0,
				'order' => 35,
			],
			[
				'key' => 'landing_backdrop_opacity',
				'value' => '0',
				'cat' => self::MOD_WELCOME,
				'type_range' => self::PERCENT_RANGE,
				'description' => 'Global backdrop opacity (%)',
				'details' => 'Adds a black overlay in front of the background image at this opacity. Applies to every layout. 0 disables it.',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 0,
				'order' => 36,
			],
		];
	}
};
