<?php

/**
 * SPDX-License-Identifier: MIT
 * Copyright (c) 2017-2018 Tobias Reich
 * Copyright (c) 2018-2026 LycheeOrg.
 */

use App\Models\Extensions\BaseConfigMigration;

return new class() extends BaseConfigMigration {
	public const CAT = 'contact';

	public function getConfigs(): array
	{
		return [
			[
				'key' => 'contact_form_enabled',
				'value' => '0',
				'cat' => self::CAT,
				'type_range' => self::BOOL,
				'description' => 'Enable the contact form on the website',
				'details' => '',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 1,
				'order' => 1,
			],
			[
				'key' => 'contact_form_security_question',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Security question',
				'details' => 'Optional security question, if left empty, no question will be shown and no answer will be expected.',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 1,
				'order' => 2,
			],
			[
				'key' => 'contact_form_security_answer',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Expected answer for the security question',
				'details' => 'The answer to the security question (case-insensitive). Ignored if the security question is empty.',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 1,
				'order' => 3,
			],
			[
				'key' => 'contact_form_custom_consent_required',
				'value' => '0',
				'cat' => self::CAT,
				'type_range' => self::BOOL,
				'description' => 'Consent required',
				'details' => 'When set, a consent checkbox becomes required. If you need to ask users for consent (e.g. to comply with GDPR), you can set the consent text here. When set, a checkbox will be added to the form and users will have to check it before submitting the form.',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 1,
				'order' => 4,
			],
			[
				'key' => 'contact_form_custom_privacy_url',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'URL to the privacy policy',
				'details' => 'If have a privacy policy URL, you can set it here. It will be displayed as a link alongside the consent text.',
				'is_secret' => false,
				'is_expert' => false,
				'level' => 2,
				'order' => 5,
			],
			[
				'key' => 'contact_form_header',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Header of the contact form',
				'details' => 'Leave empty for default. Allows you to set a custom header for the contact form page.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 6,
			],
			[
				'key' => 'contact_form_headline',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Headline of the contact form',
				'details' => 'Leave empty for default. This allows you to provide a short description or instructions for the contact form.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 7,
			],
			[
				'key' => 'contact_form_contact_method',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Contact method',
				'details' => 'Leave empty for default. This allows you to specificy how users should expect to be contacted back (e.g. email, phone, etc.). It is just a label shown on the form, it does not have any functional effect.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 8,
			],
			[
				'key' => 'contact_form_message_label',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Label for the question field',
				'details' => 'Allows you to customize the question shown to the user. Instead of having just "message" and leaving them with a white box, you can ask them to provide specific information.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 9,
			],
			[
				'key' => 'contact_form_message_answer',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Sample answer',
				'details' => 'Optional sample answer, shown as placeholder.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 10,
			],
			[
				'key' => 'contact_form_custom_consent_text',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Consent text',
				'details' => 'When the consent checkbox is required, you can customize the text here.',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 11,
			],
			[
				'key' => 'contact_form_custom_submit_button_text',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Custom text for the submit button',
				'details' => 'Default if empty is "Send Message"',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 12,
			],
			[
				'key' => 'contact_form_thank_you_message',
				'value' => '',
				'cat' => self::CAT,
				'type_range' => self::STRING,
				'description' => 'Custom thank you message after submitting the form',
				'details' => 'Default if empty is "Thank you for your message. We will get back to you soon."',
				'is_secret' => false,
				'is_expert' => true,
				'level' => 2,
				'order' => 13,
			],
		];
	}
};
