#!/bin/sh
NO_COLOR="\033[0m"
GREEN="\033[38;5;010m"
YELLOW="\033[38;5;011m"

echo "\n${GREEN}pre commit hook start${NO_COLOR}\n"

PHP_CS_FIXER="vendor/bin/php-cs-fixer"

if [ -x "$PHP_CS_FIXER" ]; then
    git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
        ${PHP_CS_FIXER} fix --config=.php_cs ${line};
        git add "$line";
    done
else
    echo ""
    echo "${YELLOW}Please install php-cs-fixer, e.g.:${NO_COLOR}"
    echo ""
    echo "  composer install"
    echo ""
fi

echo "\n${GREEN}pre commit hook finish${NO_COLOR}\n"
