<?php

namespace App\Http\Controllers;

use App\Actions\Album\Archive;
use App\Actions\Album\Create;
use App\Actions\Album\CreateTagAlbum;
use App\Actions\Album\Delete;
use App\Actions\Album\Merge;
use App\Actions\Album\Move;
use App\Actions\Album\PositionData;
use App\Actions\Album\SetProtectionPolicy;
use App\Actions\Album\Unlock;
use App\Contracts\AbstractAlbum;
use App\Contracts\LycheeException;
use App\DTO\PositionData as PositionDataDTO;
use App\Exceptions\MediaFileOperationException;
use App\Exceptions\ModelDBException;
use App\Http\Requests\Album\AddAlbumRequest;
use App\Http\Requests\Album\AddTagAlbumRequest;
use App\Http\Requests\Album\ArchiveAlbumsRequest;
use App\Http\Requests\Album\DeleteAlbumsRequest;
use App\Http\Requests\Album\DeleteTrackRequest;
use App\Http\Requests\Album\GetAlbumPositionDataRequest;
use App\Http\Requests\Album\GetAlbumRequest;
use App\Http\Requests\Album\MergeAlbumsRequest;
use App\Http\Requests\Album\MoveAlbumsRequest;
use App\Http\Requests\Album\PatchAlbumRequest;
use App\Http\Requests\Album\PatchTagAlbumRequest;
use App\Http\Requests\Album\SetAlbumCoverRequest;
use App\Http\Requests\Album\SetAlbumProtectionPolicyRequest;
use App\Http\Requests\Album\SetAlbumsTitleRequest;
use App\Http\Requests\Album\SetAlbumTrackRequest;
use App\Http\Requests\Album\UnlockAlbumRequest;
use App\Models\Album;
use App\Models\Extensions\BaseAlbum;
use App\Models\TagAlbum;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\App;
use Symfony\Component\HttpFoundation\StreamedResponse;

class AlbumController extends Controller
{
	/**
	 * Add a new Album.
	 *
	 * @param AddAlbumRequest $request
	 * @param Create          $create
	 *
	 * @return Album
	 *
	 * @throws LycheeException
	 */
	public function add(AddAlbumRequest $request, Create $create): Album
	{
		return $create->create($request->title(), $request->parentAlbum());
	}

	/**
	 * Add a new album generated by tags.
	 *
	 * @param AddTagAlbumRequest $request
	 * @param CreateTagAlbum     $create
	 *
	 * @return TagAlbum
	 *
	 * @throws LycheeException
	 */
	public function addTagAlbum(AddTagAlbumRequest $request, CreateTagAlbum $create): TagAlbum
	{
		return $create->create($request->title(), $request->tags());
	}

	/**
	 * Provided an albumID, returns the album.
	 *
	 * @param GetAlbumRequest $request
	 *
	 * @return AbstractAlbum
	 */
	public function get(GetAlbumRequest $request): AbstractAlbum
	{
		return $request->album();
	}

	/**
	 * Provided an albumID, returns the album with only map related data.
	 *
	 * @param GetAlbumPositionDataRequest $request
	 * @param PositionData                $positionData
	 *
	 * @return array
	 */
	public function getPositionData(GetAlbumPositionDataRequest $request, PositionData $positionData): PositionDataDTO
	{
		return $positionData->get($request->album(), $request->includeSubAlbums());
	}

	/**
	 * Provided the albumID and password, return whether the album can be accessed or not.
	 *
	 * @param UnlockAlbumRequest $request
	 * @param Unlock             $unlock
	 *
	 * @return void
	 *
	 * @throws LycheeException
	 */
	public function unlock(UnlockAlbumRequest $request, Unlock $unlock): void
	{
		$unlock->do($request->album(), $request->password());
	}

	/**
	 * Provided a title and albumIDs, change the title of the albums.
	 *
	 * @param SetAlbumsTitleRequest $request
	 *
	 * @return void
	 *
	 * @throws LycheeException
	 */
	public function setTitle(SetAlbumsTitleRequest $request): void
	{
		/** @var BaseAlbum $album */
		foreach ($request->albums() as $album) {
			$album->title = $request->title();
			$album->save();
		}
	}

	/**
	 * Update an album.
	 *
	 * @param PatchAlbumRequest $request
	 *
	 * @return void
	 *
	 * @throws ModelDBException
	 */
	public function patchAlbum(PatchAlbumRequest $request): void
	{
		/** @var Album $album */
		foreach ($request->albums() as $album) {
			if ($request->license() !== null) {
				$album->license = $request->license();
			}
			if ($request->isNSFW() !== null) {
				$album->is_nsfw = $request->isNSFW();
			}
			if ($request->hasDescription()) {
				$album->description = $request->description();
			}
			if ($request->title() !== null) {
				$album->title = $request->title();
			}
			if ($request->hasSorting()) {
				$album->sorting = $request->sortingCriterion();
			}
			$album->save();
		}
	}

	/**
	 * Update a tag album.
	 *
	 * @param PatchTagAlbumRequest $request
	 *
	 * @return void
	 *
	 * @throws ModelDBException
	 */
	public function patchTagAlbum(PatchTagAlbumRequest $request): void
	{
		/** @var TagAlbum $album */
		foreach ($request->albums() as $album) {
			if ($request->isNSFW() !== null) {
				$album->is_nsfw = $request->isNSFW();
			}
			if ($request->hasDescription()) {
				$album->description = $request->description();
			}
			if ($request->title() !== null) {
				$album->title = $request->title();
			}
			if ($request->hasSorting()) {
				$album->sorting = $request->sortingCriterion();
			}
			if ($request->tags() !== null) {
				$album->show_tags = $request->tags();
			}
			$album->save();
		}
	}

	/**
	 * Upload a track for the Album.
	 *
	 * @param SetAlbumTrackRequest $request
	 *
	 * @return void
	 *
	 * @throws MediaFileOperationException
	 * @throws ModelDBException
	 */
	public function setTrack(SetAlbumTrackRequest $request): void
	{
		$request->album()->setTrack($request->file);
	}

	/**
	 * Delete a track from the Album.
	 *
	 * @param DeleteTrackRequest $request
	 *
	 * @return void
	 *
	 * @throws ModelDBException
	 */
	public function deleteTrack(DeleteTrackRequest $request): void
	{
		$request->album()->deleteTrack();
	}

	/**
	 * Delete the album and all of its pictures.
	 *
	 * @param DeleteAlbumsRequest $request the request
	 * @param Delete              $delete  the delete action
	 *
	 * @return void
	 *
	 * @throws ModelDBException
	 * @throws MediaFileOperationException
	 */
	public function delete(DeleteAlbumsRequest $request, Delete $delete): void
	{
		$fileDeleter = $delete->do($request->albumIDs());
		App::terminating(fn () => $fileDeleter->do());
	}

	/**
	 * Merge albums. The first of the list is the destination of the merge.
	 *
	 * @param MergeAlbumsRequest $request
	 * @param Merge              $merge
	 *
	 * @return void
	 *
	 * @throws LycheeException
	 * @throws ModelNotFoundException
	 */
	public function merge(MergeAlbumsRequest $request, Merge $merge): void
	{
		$merge->do($request->album(), $request->albums());
	}

	/**
	 * Move multiple albums into another album.
	 *
	 * @param MoveAlbumsRequest $request
	 * @param Move              $move
	 *
	 * @return void
	 *
	 * @throws LycheeException
	 * @throws ModelNotFoundException
	 */
	public function move(MoveAlbumsRequest $request, Move $move): void
	{
		$move->do($request->album(), $request->albums());
	}

	/**
	 * Sets the protection policy of the album.
	 *
	 * @param SetAlbumProtectionPolicyRequest $request
	 * @param SetProtectionPolicy             $setProtectionPolicy
	 *
	 * @return void
	 *
	 * @throws LycheeException
	 */
	public function setProtectionPolicy(SetAlbumProtectionPolicyRequest $request, SetProtectionPolicy $setProtectionPolicy): void
	{
		$setProtectionPolicy->do(
			$request->album(),
			$request->albumProtectionPolicy(),
			$request->isPasswordProvided(),
			$request->password()
		);
	}

	/**
	 * Set cover image of the album.
	 *
	 * @param SetAlbumCoverRequest $request
	 *
	 * @return void
	 *
	 * @throws ModelDBException
	 */
	public function setCover(SetAlbumCoverRequest $request): void
	{
		$request->album()->cover_id = $request->photo()?->id;
		$request->album()->save();
	}

	/**
	 * Return the archive of the pictures of the album and its sub-albums.
	 *
	 * @param ArchiveAlbumsRequest $request
	 * @param Archive              $archive
	 *
	 * @return StreamedResponse
	 *
	 * @throws LycheeException
	 */
	public function getArchive(ArchiveAlbumsRequest $request, Archive $archive): StreamedResponse
	{
		return $archive->do($request->albums());
	}
}
