<?php


namespace App\SmartAlbums;


class TagAlbum extends SmartAlbum
{

	public $tags = array();

	public function get_title()
	{
		return 'tag-testing'; // TODO: Change the autogenerated stub
	}


	public function get_photos()
	{
		return parent::get_photos(); // TODO: Change the autogenerated stub
	}


	public function is_public()
	{
		return true; // TODO: Change the autogenerated stub
	}


}