<?php

namespace App\SmartAlbums;

use App\ModelFunctions\AlbumFunctions;
use App\ModelFunctions\SessionFunctions;

class TagAlbum extends SmartAlbum
{
	public $tags = [];

	private $title = 'tag-noname';

	/**
	 * TagAlbum constructor.
	 *
	 * @param AlbumFunctions   $albumFunctions
	 * @param SessionFunctions $sessionFunctions
	 * @param $title
	 */
	public function __construct(AlbumFunctions $albumFunctions, SessionFunctions $sessionFunctions, $title)
	{
		parent::__construct($albumFunctions, $sessionFunctions);
		//$this->title = 'tag-' . $title;
	}

	public function get_title()
	{
		return $this->title;
	}

	public function get_photos()
	{
		return parent::get_photos(); // TODO: Change the autogenerated stub
	}

	public function is_public()
	{
		return true; // TODO: Change the autogenerated stub
	}
}