name: PR dependency check

on:
  pull_request_target: 
    types: [opened, edited, closed, reopened]

permissions:
  contents: read

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check Dependencies
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - uses: gregsdennis/dependencies-action@4fc2a4879387b43f784920699cb9303dd0524ac4 # 1.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}